name: Deploy Supabase Edge Function (fets-ai-proxy)

on:
  push:
    branches:
      - main # Or your primary branch, e.g., master
    paths:
      - 'supabase/functions/fets-ai-proxy/**' # Trigger only if files in this path change
      - '.github/workflows/deploy_supabase_function.yml' # Or if the workflow file itself changes
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  deploy-fets-ai-proxy:
    runs-on: ubuntu-latest
    environment: production # Optional: if you set up environments in GitHub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest # You can pin to a specific version, e.g., v1.160.0

      - name: Deploy fets-ai-proxy Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }} # Using SUPABASE_PROJECT_REF
        run: |
          echo "Linking to project $SUPABASE_PROJECT_REF"
          supabase link --project-ref $SUPABASE_PROJECT_REF
          echo "Deploying fets-ai-proxy function..."
          supabase functions deploy fets-ai-proxy --project-ref $SUPABASE_PROJECT_REF --no-verify-jwt
          echo "Deployment attempt finished."